fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.11.0
  symlinks:
    osc_facts: "#{source_dir}"
    nfsroot: "#{source_dir}/../nfsroot"
