fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.11.0
    nfsroot:
      repo: https://github.com/treydock/puppet-nfsroot
  symlinks:
    treydock_stdlib: "#{source_dir}"
