---
.travis.yml:
  dist: xenial
  deploy: false
  user: treydock
  secure: "jXxA5dFxh6Y91N7KlFJRvvZosQXwUj6iKH5Jbq8ZQpdHoGaR2+0wxJHk0pvgY9nyLrbamPbokDmtmdX/+Dzc5fW1UXDz/GyB0Nk6y1KyRQh3z2mStnRejdLpyUPYXyxd8WC37m+792S8utyYfGjCKtz5/jv55xo+f1M6wDzfH71Ol7HugqiixwSEOiYl6G3qhOt/SOgtAwX2lAoEp/JqMZf7YinuXCkq8a3QZVLyMghheoThzRql60doCdo1LT2KDIfk5yZojndxMJiI+30euLhyCbpeGMVqWzpJaWBPVTVsYfgRwzcswrw3xHLFuieI5nZLRHg0F4TqizIAUjQaEaGM3E9b7/QVsn4lYd7iYQkQCFQEIB5zgRi9VSyulhmyvHYwsVdpvosLWAzSIrPetamSlOtwsA7KxeznCdryI3Jpz3ffjFERh0Wgjc4aZ1HFSXL7KfSrMDkY+CfEVe7h/gCdvMy3Wl/97/+iU6aPfkWdH3KUq5kfdtfPoIAtgdfkJkBpvDEjWbbT6GNhAet0QrpkblksIra57Z/lj+sAb/8ICacMr6IBQQ++riEM1z+Fx3AyeCbPoaCCQ8aCZafAq0EndpmqjD4mm4/TzG0wY3ia/O30ea9Q9Ex34Wknr8nrdtBkz6bZIh5ajQPxuzlhLgJ/XZ8IulQtkqeUDJqAmg8="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/spec_helper_acceptance.rb:
  delete: true
spec/acceptance/nodesets/centos-6.yml:
  delete: true
spec/acceptance/nodesets/centos-7.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
